window.ADMIN_SEED_PRODUCTS = [
  { product_no:'100001', name:'經典蜜汁', price:200, cost:80.5, specification:'200 克／包', description:'品名：蜜汁原味豬肉條\n成分：台灣後腿豬肉、糖、海藻糖、鹽、醬油、棕櫚油、肉桂粉\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：本產品含大豆及其製品', image_url:'', sort_order:1, enabled:true },
  { product_no:'100002', name:'台式蒜香', price:200, cost:80.5, specification:'200 克／包', description:'品名：蒜味豬肉條\n成分：台灣後腿豬肉、糖、海藻糖、蒜粉、鹽、醬油、棕櫚油、肉桂粉\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：本產品含大豆及其製品', image_url:'', sort_order:2, enabled:true },
  { product_no:'100003', name:'嚴選胡椒', price:200, cost:80.5, specification:'200 克／包', description:'品名：黑胡椒豬肉條\n成分：台灣後腿豬肉、糖、海藻糖、黑胡椒、鹽、醬油、棕櫚油、大茴、丁香、肉桂\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：本產品含大豆及其製品', image_url:'', sort_order:3, enabled:true },
  { product_no:'100004', name:'泰式酸辣', price:200, cost:80.5, specification:'200 克／包', description:'品名：泰式酸辣豬肉條\n成分：台灣後腿豬肉、糖、海藻糖、鹽、辣椒粒、辣椒粉、醬油、檸檬精、棕櫚油\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：本產品含大豆及其製品', image_url:'', sort_order:4, enabled:true },
  { product_no:'100005', name:'川辣', price:200, cost:80.5, specification:'200 克／包', description:'品名：川辣豬肉條\n成分：豬後腿肉（台灣豬）、糖、海藻糖、大豆油、鹽、辣椒、花椒、白酒、蒜頭、胡椒、醬油、小茴香、桂皮、荳蔻、八角、丁香、陳皮、甘草、酵母提取物\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：本產品含大豆及其製品', image_url:'', sort_order:5, enabled:true },
  { product_no:'100006', name:'濃郁起司', price:220, cost:95, specification:'200 克／包', description:'品名：濃郁起司豬肉條\n成分：台灣後腿豬肉、糖、起司粉、海藻糖、鹽、醬油、肉桂粉\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：本產品含大豆及其製品', image_url:'', sort_order:6, enabled:true },
  { product_no:'100007', name:'波波魚卵', price:230, cost:101, specification:'200 克／包', description:'品名：魚卵豬肉條\n成分：台灣後腿豬肉、糖、魚卵、海藻糖、鹽、醬油、芥花油、肉桂粉\n食品添加物：D-山梨醇液（甜味劑）、L-麩酸鈉（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號、黃色5號、黃色6號\n過敏原：本產品含大豆、魚及其製品', image_url:'', sort_order:7, enabled:true },
  { product_no:'100008', name:'奢華松露', price:250, cost:115, specification:'200 克／包', description:'品名：黑松露肉條\n成分：台灣豬後腿肉、糖、松露醬、海藻糖、鹽、醬油、肉桂粉\n食品添加物：D-山梨醇液（甜味劑）、味精（調味劑）、己二烯酸鉀（防腐劑）、多磷酸鈉（品質改良劑）、異抗壞血酸鈉（抗氧化劑）、亞硝酸鈉（保色劑）、食用色素紅色40號\n過敏原：請參閱成分', image_url:'', sort_order:8, enabled:true },
  { product_no:'200001', name:'全家大小都會愛－經典蜜汁、台式蒜香、泰式酸辣', price:585, cost:0, specification:'200 克／包，共 3 包', description:'送禮三件組。商品內容已完整標示於商品名稱，備貨時依商品名稱準備。', image_url:'', sort_order:9, enabled:true },
  { product_no:'200002', name:'就愛火辣辣－經典蜜汁、川辣、嚴選胡椒', price:585, cost:0, specification:'200 克／包，共 3 包', description:'送禮三件組。商品內容已完整標示於商品名稱，備貨時依商品名稱準備。', image_url:'', sort_order:10, enabled:true },
  { product_no:'200003', name:'老饕私藏限定－經典蜜汁、波波魚卵、奢華松露', price:655, cost:0, specification:'200 克／包，共 3 包', description:'送禮三件組。商品內容已完整標示於商品名稱，備貨時依商品名稱準備。', image_url:'', sort_order:11, enabled:true }
];
